### PR TITLE
Adding list of Python packages

### PR DESCRIPTION
**Pull request by tmtabor**

### CODE REVIEW

**Review by bahill — COMMENTED** [review]
Hey Thorin, 

Looks good to me. One question though - what does the bolding mean?

**Review by bahill — COMMENTED** [review]
Also - why do only a few get links - just for doc?

**Comment by tmtabor** [comment]
There are 158 items in the list. I have little idea what the bulk of those packages do. I believe that the majority of our users are also going to have little idea what the bulk of those packages do.

That said, some of those packages are more interesting than others. The bolding is intended to draw attention to packages that might be of interest - to help tease signal from the noise.

Two of those packages are linked because those are the ones that were explicitly asked for in today's meeting. Otherwise, my assumption is that programmatic users are mostly going to come to this list to see if a preferred package is included. (Or more likely, they're going to skip the website entirely and just run `pip freeze` or `conda list`.) In that use case, the user already knows what the package in question does, so linking out is of little benefit.

In the other use case, where a user is going to the website to explore what packages are available, I would argue that the list is way too noisy to be particularly useful in that task. (Or at least I wouldn't blindly click 158 links to see where they go.) That said, I might click one or two links is those were called out as important for some reason.

**Review by bahill — APPROVED** [review]
Well that all makes sense to me!

**Pull request merged**
